export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_UNKNOWN: 'AUTH_UNKNOWN',

  LISTS_NOT_FOUND: 'LISTS_NOT_FOUND',
  LISTS_FORBIDDEN: 'LISTS_FORBIDDEN',
  LISTS_UNKNOWN: 'LISTS_UNKNOWN',

  ITEMS_NOT_FOUND: 'ITEMS_NOT_FOUND',
  ITEMS_FORBIDDEN: 'ITEMS_FORBIDDEN',
  ITEMS_UNKNOWN: 'ITEMS_UNKNOWN',

  INVITES_INVALID: 'INVITES_INVALID',
  INVITES_EXPIRED: 'INVITES_EXPIRED',
  INVITES_UNKNOWN: 'INVITES_UNKNOWN',

  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
